//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPSWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPSIntegrationEntities : DbContext
    {
        public UPSIntegrationEntities()
            : base("name=UPSIntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_UPSOnDemantPickup_Order> B_UPSOnDemantPickup_Order { get; set; }
        public virtual DbSet<TEMCargo_ililcekodlari> TEMCargo_ililcekodlari { get; set; }
        public virtual DbSet<UPSCargoililcekodlari> UPSCargoililcekodlari { get; set; }
    }
}
