//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPSWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMCargo_ililcekodlari
    {
        public int id { get; set; }
        public string il { get; set; }
        public string ilce_Semt { get; set; }
        public Nullable<int> il_kodu { get; set; }
        public Nullable<int> ilceSemt_kodu { get; set; }
    }
}
